version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: recruiting-frontend
    networks:
      - recruiting
    ports:
      - "3000:3000"

networks:
  recruiting:
    external: true
