version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: authframework-frontend
    networks:
      - authframework
    ports:
      - "3000:3000"

networks:
  authframework:
    external: true
